"""Initial migration

Revision ID: fad127837c2a
Revises: 
Create Date: 2017-01-21 12:13:41.053656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad127837c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'posts_tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'posts_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
